### ISSUE TITLE
Sanitization parity with Java SDKs

### ISSUE THREAD

**Issue by hanwavefront** [wavefrontHQ/wavefront-sdk-csharp#48]
wavefrontHQ/wavefront-sdk-java@fd04182
wavefrontHQ/wavefront-sdk-java@1d7dd10

**Comment by vikramraman** [comment]
Note that within Java source values of the form `host:port` are currently converted to `host-port` as part of the sanitization process. It'd be preferable to retain the colon in source values as they are valid characters.

wavefrontHQ/wavefront-sdk-java#148 for reference.
